### PR TITLE
Fix sid rules file

### PR DESCRIPTION
**Pull request by scpeters**
An attempt to fix the Sid debbuild:

* [Build Status](https://build.osrfoundation.org/job/ign-utils1-debbuilder/399/) https://build.osrfoundation.org/job/ign-utils1-debbuilder/399/

### CODE REVIEW

**Comment by scpeters** [comment]
testing:

* [Build Status](https://build.osrfoundation.org/job/ign-utils1-debbuilder/401/) https://build.osrfoundation.org/job/ign-utils1-debbuilder/401/

**Comment by j-rivero** [comment]
launch a new build on Debian to check changes. Afterwards we would need to run a new -2 release to get it uploaded properly.

**Comment by scpeters** [comment]
> launch a new build on Debian to check changes. Afterwards we would need to run a new -2 release to get it uploaded properly.

looks good to me

[Build Status](https://build.osrfoundation.org/job/ign-utils1-debbuilder/403/) https://build.osrfoundation.org/job/ign-utils1-debbuilder/403/

**Review by j-rivero — APPROVED** [review]

**Comment by j-rivero** [comment]
I'll launch the -2 builds

**Pull request merged**
