### PR TITLE
Add libignition-utils-cli-dev

### PR DESCRIPTION
**Pull request by scpeters**
Adds another package for the cli component. Targeted at #3.

### CODE REVIEW

**Comment by scpeters** [comment]
testing:  [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/29/) https://build.osrfoundation.org/job/ign-utils-debbuilder/29/

**Comment by scpeters** [comment]
> testing: [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/29/) https://build.osrfoundation.org/job/ign-utils-debbuilder/29/

test build looks good

**Comment by j-rivero** [comment]
To avoid possible conflicts with unversioned `-dev` in Ubuntu/Debian, how about adding using `libignition-utils-cli1-dev` as package name?

**Comment by scpeters** [comment]
> To avoid possible conflicts with unversioned `-dev` in Ubuntu/Debian, how about adding using `libignition-utils-cli1-dev` as package name?

have we done this before: putting the major version on the component instead of the package name? i.e. which if the two do we want:

* `libignition-utils1-cli-dev`
* `libignition-utils-cli1-dev`

**Comment by chapulina** [comment]
> which if the two do we want:

`libignition-utils1-cli-dev` makes more sense to me. I believe the unversioned one on debian would be `libignition-utils-cli-dev`, right?

**Comment by j-rivero** [comment]
> `libignition-utils1-cli-dev` makes more sense to me.

This I think is the right option. es the unversioned version in debian would be like that.

> I believe the unversioned one on debian would be `libignition-utils-cli-dev`, right?

right

**Comment by scpeters** [comment]
ok, the thing that's confusing me is that we don't have versions in any of the other package names. we currently have:

* `libignition-utils`
* `libignition-utils-dev`
* `libignition-utils-dbg`

so it seems weird to add `libignition-utils1-cli-dev`, which doesn't match the other packages. should we change them all to start with `libignition-utils1`?

**Comment by chapulina** [comment]
> we don't have versions in any of the other package names

Good point, my understanding is that we were going to change those to `utils1` so we leave `utils` open for the upstream debian packages

**Comment by scpeters** [comment]
> > we don't have versions in any of the other package names
> 
> Good point, my understanding is that we were going to change those to `utils1` so we leave `utils` open for the upstream debian packages

so change all of them in this PR?

**Comment by scpeters** [comment]
> > > we don't have versions in any of the other package names
> > 
> > 
> > Good point, my understanding is that we were going to change those to `utils1` so we leave `utils` open for the upstream debian packages
> 
> so change all of them in this PR?

ok, I can update this PR, but we'll need to update all the packages.apt files and other -release repos that refer to `libignition-utils-dev`

**Comment by j-rivero** [comment]
mental note: other packages depend on previous unversion name, try to use Provides to keep things working or add a transitional package.

**Comment by j-rivero** [comment]
Moved metadata to versioned -dev files. Testing here [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/37/)

**Comment by scpeters** [comment]
ok, I've fixed some package names a bit more and testing again: [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/40/) https://build.osrfoundation.org/job/ign-utils-debbuilder/40/

**Comment by scpeters** [comment]
> ok, I've fixed some package names a bit more and testing again: [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/40/) https://build.osrfoundation.org/job/ign-utils-debbuilder/40/

ok your turn @j-rivero, what did I do wrong?

~~~
dpkg-source: error: source package has two conflicting values - ignition-utils1 and ignition-utils
~~~

**Comment by j-rivero** [comment]
> ok your turn @j-rivero, what did I do wrong?

The source package name is defined in two different places that must be in sync: control file and changelog. Debian typically use the one defined by CMakeListst.txt in the `project` clause. I changed it in the changelogs in da8807c 

New run: [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/43/)

**Comment by scpeters** [comment]
new build: [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/46/) https://build.osrfoundation.org/job/ign-utils-debbuilder/46/

**Comment by scpeters** [comment]
> new build: [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/46/) https://build.osrfoundation.org/job/ign-utils-debbuilder/46/

that was a bionic build; here's focal:

* [Build Status](https://build.osrfoundation.org/job/ign-utils-debbuilder/47/) https://build.osrfoundation.org/job/ign-utils-debbuilder/47/

**Comment by scpeters** [comment]
I think this is safe to be merged now. After the focal build finishes, there will be both versioned and unversioned debs in the nightly repository (`libignition-utils-dev` and `libignition-utils1-dev`), which will simplify the timing of updating `packages.apt` files to reference the versioned debs

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
